version: 0.0
os: linux

files:
  - source: /
    destination: /home/damataxi
permissions:
  - object: /home/damataxi/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: /home/ubuntu/codedeploy.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
