version: 0.0
os: linux

files:
  - source: /
    destination: /opt/damataxi
permissions:
  - object: /opt/damataxi/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
