name: CI-CD

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
    
jobs:
  test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test
      run: ./gradlew build
  
  deploy:
  
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Make zip file 
      run: zip -r ./$GITHUB_SHA.zip . 
      shell: bash 

    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{ secrets.AWS_REGION }} 

    - name: Upload to S3 
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://damataxi/damataxi/$GITHUB_SHA.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name damataxi --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name damataxi --s3-location bucket=damataxi,bundleType=zip,key=damataxi/$GITHUB_SHA.zip
